version: 2.1
orbs:
  slack: circleci/slack@4
jobs:
  lint:
    docker:
      - image: cimg/go:1.18
    steps:
      - checkout
      - run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.45.0
      - run: make lint
      - store_test_results:
          path: test-results

  test:
    docker:
      - image: cimg/go:1.18
    steps:
      - checkout
      - run: make test
      - store_test_results:
          path: test-results
#      - slack/notify:
#          branch_pattern: main
#          event: fail
#          template: basic_fail_1

#  release:
#    docker:
#      - image: cimg/go:1.17
#    steps:
#      - slack/notify:
#          event: pass
#          template: success_tagged_deploy_1

workflows:
  version: 2
  build:
    jobs:
      - lint
      - test
#      - release:
#          filters:
#            tags:
#              only: /^v.*/
#          requires:
#            - lint
#            - test
